### ISSUE TITLE
Correction VSphere.py

### ISSUE THREAD

**Issue by Hachebourin** [ExtensiveTesting/extensivetesting#11]
Hello,

Je n'ai pas encore regardé comment faire de pull request alors en attendant je fais une issue :

Il y a une petite erreur à cause d'une mauvais nom de variable. Dans le fichier TestInteropLib/VSphere.py,
fonction cloneVm, dans le content des logs, la variable vmName n'existe pas :            

```
content = { "result": "success",  "cmd": "clone-vm", 'vm-name': vmName }
tpl = self.template(name=self.__class__.__name__.upper(), content=content )
self.logResponse(msg="clone vm", details=tpl )
```

Je crois qu'il faut remplacer vmName par toVm. Ce n'est pas bloquant mais dans les logs XTC on obtient toujours une erreur de clonage.

**Comment by dmachard** [comment]
corrigé sur les 2 branches, merci
le fix sera intégré dans la prochaine version j'ai supprimé la clé directement
