### ISSUE TITLE
Telnet Adapter error: « unable to pack options : need more than 1 value to unpack »

### ISSUE THREAD

**Issue by danieldds1983** [ExtensiveTesting/extensivetesting#12]
Using the Telnet client:

self.telnetObj = SutAdapters.Telnet.Client(parent=self, name=input('ADAPTER_NAME'), shared=input('SHARED'), destIp=input('TELNET_HOST'),destPort=input('TELNET_PORT'),debug=input('DEBUG'),agentSupport=input('AGENT_SUPPORT'))

The same code works for other equipment's and via Windows cmd line no problems connecting via telnet to the equipment. The output from telnet appears to have some strange characters, for other equipment I can see the login prompt, for this one no.

Output:

![error](https://user-images.githubusercontent.com/34236659/38039757-3ba2101a-32ae-11e8-8ae1-7e9d6df02560.PNG)
,

**Comment by dmachard** [comment]
Can you update the function 'sendOptions' like below in the file client.py, to add more logs ?

```
	def sendOptions(self, opts):
		.....
			if cmd in codec.TELNET_COMMANDS:
				cmds_str = '%s' % codec.TELNET_COMMANDS[cmd]
			else:
				self.warning("telnet command not supported: %s" % cmd)
			if opt in codec.TELNET_OPTIONS:
				cmds_str += ' %s' % codec.TELNET_OPTIONS[opt]
			else:
				self.warning("telnet option not supported: %s" % opt)
			tpl_cmds.addKey(name="%s" % nb_cmd, data=cmds_str)
	       .....
```

**Comment by danieldds1983** [comment]
Event 8 details:

![event8](https://user-images.githubusercontent.com/34236659/38085342-6bee0c04-3350-11e8-95c1-e035987ec4af.PNG)

**Comment by dmachard** [comment]
issue fixed in unstable branch
will be release in next version
