### ISSUE TITLE
[Plugin QC ]Error exporting results to TestLab

### ISSUE THREAD

**Issue by danieldds1983** [ExtensiveTesting/extensivetesting#3]
When exporting results, a REST error with invalid testpath is displayed and the results are not exported.

The workaround:
- click on the plugin HP ALM QC to export the qc
- uncheck the "ignore testcase" button (the test will appear on the list)
- re-check the "ignore testcase" button (the test is still in the list)
- select the test and try to export.

Gives the error: "unable to find the test on TestPlan" (but the test is created on TestPlan)

**Comment by danieldds1983** [comment]
The workaround works with the snippet check XML. But with my testcase with several steps don't. The difference seems to be the number of steps and the path. I will check.

**Comment by Hachebourin** [comment]
Can you tell me how many test you have in your test plan in QC ?

I don't know if it's cause to this but I find a limitation last week from this service :

`/rest/domains/DOMAIN/projects/PROJECT/tests?query=PARENT_ID&page-size=X&start-index=Y`

By default, page-size=100.

X is the number of how many tests you can see at same page. Y is the number of how many tests you will "skip".

Actually, if you have more than 100 tests, the QC plugin can't get all tests.

**Comment by danieldds1983** [comment]
I have just one test. With the snippet works, but with my test gives the "unable to find the test on TestPlan" error. The export for the Test Plan works well, just the export of results fails.

**Comment by Hachebourin** [comment]
Try to put the test name in uppercase.

**Comment by danieldds1983** [comment]
Tested with uppercase and same problem. I think that something related with the path because using default path with XML snippet works. But if I change to custom path the snippet also fails

**Comment by Hachebourin** [comment]
I  reproduced the problem and in my case I have an error when the name of my test in Extensive Testing and QC is in lowercase.
In my global test, I use the Alias Name option, which puts the test name in uppercase (impossible to put it in lowercase). So, the plugin doesn't find it ...
When I put the name of my test in ET and QC in upper case and it is also in my global test I do not meet the problem and the result of the export of result works.

Are you sure the name in ET, QC and your global test are all in uppercase ?

**Comment by danieldds1983** [comment]
My test name is: QCDEMO, and is called on Test Plan file with name TTT

The test is well created on QC Test Plan with name QCDEMO, and on export step all names are uppercase. But the error occurs. If you want I could copy the source code here.

**Comment by danieldds1983** [comment]
Here it is the code of QCDEMO test:


def description(self):
	# testcase description
	self.setPurpose(purpose="Demo")

	# steps description
	self.step1 = self.addStep(expected="Login with success", description="1", summary="Open a SSH session", enabled=True)
	self.step2 = self.addStep(expected="Command sent with success", description="2", summary="Send command: show interfaces", enabled=True)
	self.step3 = self.addStep(expected="Physical interface: pfe-0/0/0, Enabled, Physical link is Up", description="3", summary="All interfaces are listed", enabled=True)
	self.step4 = self.addStep(expected="Session closed with success", description="4", summary="Close SSH session", enabled=True)

def prepare(self):
	# adapters and libraries definitions
	self.ADP_SYS = SutAdapters.SSH.Terminal(parent=self, destIp=input('SYS_DEST_HOST'),destPort=input('SYS_DEST_PORT'),login=input('SYS_LOGIN'),password=input('SYS_PWD'),agent=agent('AGENT_SYSTEM'),debug=input('DEBUG'),agentSupport=input('SYS_AGT_SUPPORT') )

	

def definition(self):
	##CAPTURE_SYS>
	if self.step1.isEnabled():
		self.step1.start()
		SYS_RET1 = self.ADP_SYS.doSession(timeout=input('TIMEOUT_SYS'))
		if not SYS_RET1:
			self.step1.setFailed("Unable to connect ")
		else:
			self.step1.setPassed("Executing with success: Login")
	
			##CAPTURE_SYS>
			if self.step2.isEnabled():
				self.step2.start()
				SYS_RET2 = self.ADP_SYS.doText(text=input('SYS_TEXT_2'))
				if not SYS_RET2:
					self.step2.setFailed("Unable to send command")
				else:
					self.step2.setPassed("Executing with success: send command")
	
					##CAPTURE_SYS>
					if self.step3.isEnabled():
						self.step3.start()
						SYS_RET3 = self.ADP_SYS.hasReceivedScreen(timeout=input('TIMEOUT_SYS'), text=TestOperators.Contains(needle=input('SYS_SCREEN_3')))
						if not SYS_RET3:
							self.step3.setFailed("Unable to check interface")
						else:
							self.step3.setPassed("Executing with success: check interface")
	
							##CAPTURE_SYS>
							if self.step4.isEnabled():
								self.step4.start()
								SYS_RET4 = self.ADP_SYS.doClose(timeout=input('TIMEOUT_SYS'))
								if not SYS_RET4:
									self.step4.setFailed("Unable to close session")
								else:
									self.step4.setPassed("Executing with success: close session")
	

def cleanup(self, aborted):
	pass

**Comment by Hachebourin** [comment]
Ok. I'm not using it exactly like this.

In my case, a Test Plan in ET is a Test Plan in QC. As you do.

However, to import a result, you have to create a Test Global in ET (yellow icon) and add your Test Plan (TTT). Then, you can launch your Test Global and export the result. 

To resume : Test Global            > Test Plan  > Test Suite or Unit  
                   test_global_name  > TTT          > QCDEMO

In your case, in QC, your Test Plan name should be TTT. 

It's the way I use the plugin. I hope it will solve your problem :)

**Comment by Hachebourin** [comment]
In your Test Global, you have to rename your Test Plan name by using the "Alias name" button.

**Comment by danieldds1983** [comment]
Continues to not work for me. I have the test QCDEMO on QC TestPlan (//Generated Tests/QBT/POC_Autom/TTT/). I created a GLOBAL.tgx that call the TTT.tpx, that call the QCDEMO.tux. All names in uppercase. I run the global test. When I export the testcase I have the same error. When I try to export the test plan I have the same error. Probably I'm doing something wrong, but I don't know what...

**Comment by danieldds1983** [comment]
Just one question, why the Snippet XML works without Global test? And if I use custom paths to write the results don't work anymore?
Thanks!

**Comment by Hachebourin** [comment]
In QC, your TestPlan name should be TTT. Is it right ?

I send you a pdf with an example that show how I use the QC plugin.
[tuto_qc.pdf](https://github.com/dmachard/extensive-testing/files/1530737/tuto_qc.pdf)

About the Snippet XML, I don't know why it works. Do you have change something manually in the XML before exporting the result ?

**Comment by danieldds1983** [comment]
Many thanks for your support! I finally did it following exactly your steps. The problem seems to be the "Remote Test Set Path" when we export to QC Testplan. If I use the default one (//TEMP) it works. But if export it to a different path the error occurs.

For the XML I don't change anything. It's the same problem, with custom paths on the export windows, also fails.

**Comment by danieldds1983** [comment]
I'm able to export  results without Global Test. We can't change the default path when exporting to Test Plan, because when trying to export results afterwards it fails.

**Comment by Hachebourin** [comment]
Indeed, I managed to reproduce your problem. When you change the default path, you can't export result.

For the moment it's a limitation. The best practice is to create your tree structure in ET. Then, you can export in QC with default values. 

Thanks for your return.

**Comment by danieldds1983** [comment]
Thank you for your support.

**Comment by dmachard** [comment]
workaround provided by hachebourin
ticket closed
