### ISSUE TITLE
Regression version 18

### ISSUE THREAD

**Issue by Hachebourin** [ExtensiveTesting/extensivetesting#9]
Hello,

Voici deux soucis que j'ai rencontré lors de l'installation de la version 18 : 

- Il manque une tabulation dans le bloc prepare (lors de l’utilisation des adapters sikulix et selenium)

![xtcerrr](https://user-images.githubusercontent.com/19730082/37956949-ffdc0e20-31ac-11e8-96b2-8640f4dbba08.png)

Du coup, on est obligé de rajouter la tabulation à la main à chaque modification via l’assistant.

**Comment by dmachard** [comment]
pour le 1er point, le bug existe seulement si on exporte vers un test suite

Tu peux ouvrir un second ticket pour le 2ième point ? 1 pb/1 amélioration par ticket stp ;) sinon les fils de discussions vont ressembler à rien

**Comment by Hachebourin** [comment]
Pas de soucis !

**Comment by dmachard** [comment]
corrigé dans la branche stable et unstable
le fix sera intégré dans la prochaine release
merci
